on:
  push:
    branches:
    - master
name: deploy to darka mc server
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 4791.node.apexhosting.gdn
        username: Darklord2996.1976442
        password: ${{ secrets.ftp_password }}
        server-dir: ./default/
  
    - name: RCON Reload
      uses: Plagiatus/RCON-Action@v0.2
      with:
        server: ${{ secrets.rcon_server }}
        port: ${{ secrets.rcon_port }}
        password: ${{ secrets.rcon_password }}
        commands: '["say Reloading!", "reload"]'
